modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="natures_aid"
version="22.3.23"
displayName="Nature's Aid"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/natures-aid"
logoFile="logo.png"
authors="Alm, ACT"
description='''
A brand new way to play Minecraft in an ecological way.
'''

[[dependencies.natures_aid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




